#!/bin/bash

(cd src/ProcessingStarter;
    func azure functionapp publish ProcessingStarter)
(cd src/ProcessRed;
    func azure functionapp publish ProcessRed)
(cd src/ProcessBlue;
    func azure functionapp publish ProcessBlue)
