pr:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'ProcessingStarter dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output_ProcessingStarter'
    projects: '**/ProcessingStarter.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false

- task: ArchiveFiles@2
  displayName: "ProcessingStarter archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output_ProcessingStarter"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/ProcessingStarter_build$(Build.BuildId).zip"

- task: AzureFunctionApp@2
  displayName: "ProcessingStarter Deploy"
  inputs:
    azureSubscription: 'isarust-conn'
    appType: 'functionApp'
    appName: 'ProcessingStarter'
    deployToSlotOrASE: true
    resourceGroupName: 'isarust-demo-rg'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/ProcessingStarter_build$(Build.BuildId).zip'
    deploymentMethod: 'auto'

- task: DotNetCoreCLI@2
  displayName: 'ProcessBlue dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output_ProcessBlue'
    projects: '**/ProcessBlue.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false

- task: ArchiveFiles@2
  displayName: "ProcessBlue archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output_ProcessBlue"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/ProcessBlue_build$(Build.BuildId).zip"

- task: AzureFunctionApp@2
  displayName: "ProcessBlue Deploy"
  inputs:
    azureSubscription: 'isarust-conn'
    appType: 'functionApp'
    appName: 'ProcessBlue'
    deployToSlotOrASE: true
    resourceGroupName: 'isarust-demo-rg'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/ProcessBlue_build$(Build.BuildId).zip'
    deploymentMethod: 'auto'

- task: DotNetCoreCLI@2
  displayName: 'ProcessRed dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output_ProcessRed'
    projects: '**/ProcessRed.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false

- task: ArchiveFiles@2
  displayName: "ProcessRed archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output_ProcessRed"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/ProcessRed_build$(Build.BuildId).zip"

- task: AzureFunctionApp@2
  displayName: "ProcessRed Deploy"
  inputs:
    azureSubscription: 'isarust-conn'
    appType: 'functionApp'
    appName: 'ProcessRed'
    deployToSlotOrASE: true
    resourceGroupName: 'isarust-demo-rg'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/ProcessRed_build$(Build.BuildId).zip'
    deploymentMethod: 'auto'
